Repository OpenShot/openshot-qt, pull requests merged in 2019-10, with the labels that each got.

#2960 Prev/Next Marker: Auto-scroll timeline to follow playhead when it moves offscreen
  src/images/Humanity/actions/custom/center-on-playhead.svg
  src/images/openshot.qrc
  src/images/openshot_rc.py
  src/settings/_default.settings
  src/timeline/js/controllers.js
  src/windows/main_window.py
  src/windows/preview_thread.py
  src/windows/ui/main-window.ui
  src/windows/views/timeline_webview.py
Labels: interface

#2916 darkPalette: More complete disabled color group
  src/classes/app.py
  src/windows/export.py
Labels: closer, interface

#3045 CONTRIBUTING: Correct filename of openshot logfile
  CONTRIBUTING.md
Labels: docs

#3009 Profile dialog: Remove skip_first, fix loading
  src/windows/profile.py
Labels: interface
