Repository OpenShot/openshot-qt, pull requests merged in 2019-09, with the labels that each got.

#3004 Set scale=none on audio clips when splitting audio
  src/windows/views/timeline_webview.py
Labels: bug, workaround

#2964 Fix render progress display in Animated Titles editor
  src/windows/views/blender_listview.py
Labels: interface

#2951 Use openshot.OPENSHOT_VERSION_FULL for version checking
  src/classes/app.py
  src/classes/metrics.py
  src/classes/project_data.py
Labels: libopenshot

#2997 Properties: Ignore overlapping context menu events
  src/windows/views/properties_tableview.py
Labels: closer, interface, needs testing

#2836 Improve Video Preview background contrast
  src/windows/video_widget.py
Labels: interface

#2982 eval_js: Less severe logs, longer delays
  src/windows/views/timeline_webview.py
Labels: closer
