Repository OpenShot/openshot-qt, pull requests merged in 2020-09, with the labels that each got.

#3327 Add support for cqp setting in Export dialog
  src/windows/export.py
Labels: libopenshot

#3700 Fix "Add track" action (toolbar icon, keyboard shortcut)
  src/classes/logger_libopenshot.py
  src/classes/metrics.py
  src/classes/thumbnail.py
  src/classes/version.py
  src/classes/waveform.py
  src/timeline/js/controllers.js
  src/windows/animated_title.py
  src/windows/main_window.py
  src/windows/preview_thread.py
Labels: interface

#3711 Fix large canvas rendering (at closest zoom levels), with WebEngine
  src/timeline/index.html
  src/timeline/js/controllers.js
  src/timeline/js/directives/ruler.js
  src/timeline/js/functions.js
Labels: timeline, 📅 Daily Build
