Repository OpenShot/openshot-qt, pull requests merged in 2020-04, with the labels that each got.

#3331 Title editor: Convert opacity to QColor alpha level
  src/windows/title_editor.py
Labels: closer, interface

#3398 appdata: add <provides>
  xdg/org.openshot.OpenShot.appdata.xml
Labels: OS:Linux

#3394 Docs: Add Sphinx directive for youtube embeds
  doc/conf.py
  doc/youtube_directive.py
Labels: docs
