Repository OpenShot/openshot-qt, pull requests merged in 2020-05, with the labels that each got.

#3454 Use Github Actions to auto-generate user guide HTML
  .github/workflows/sphinx.yml
  doc/requirements.txt
  src/classes/info.py
Labels: docs

#3421 Blender: Use self.process consistently, fix project file discovery for Picture Frame
  src/blender/picture_frames_4.xml
  src/windows/views/blender_listview.py
Labels: closer

#3441 File Properties: Some tweaks to raise the profile of the JSON data dump
  src/windows/ui/file-properties.ui
Labels: interface

#3447 Slice shortcuts
  src/settings/_default.settings
  src/windows/main_window.py
Labels: closer, interface

#3479 json_data: Fix path_regex to support all valid JSON files
  src/classes/json_data.py
Labels: project data

#3402 [#1363] Keyframe navigation as marker
  src/windows/main_window.py
  src/windows/ui/main-window.ui
Labels: closer, interface

#3017 Simplify Unity Launcher logic
  src/classes/info.py
  src/windows/main_window.py
Labels: OS:Linux

#3495 files_treeview: Fix context menu view switching
  src/windows/views/files_treeview.py
Labels: interface

#3501 Toggle fullscreen without losing other state
  src/windows/main_window.py
Labels: interface

#3497 Overhaul of models, views, data management
  src/classes/app.py
  src/classes/info.py
  src/launch.py
  src/windows/animated_title.py
  src/windows/main_window.py
  src/windows/models/effects_model.py
  src/windows/models/emoji_model.py
  src/windows/models/files_model.py
  src/windows/models/transition_model.py
  src/windows/title_editor.py
  src/windows/views/blender_listview.py
  src/windows/views/effects_listview.py
  src/windows/views/effects_treeview.py
  src/windows/views/files_listview.py
  src/windows/views/files_treeview.py
  src/windows/views/properties_tableview.py
  src/windows/views/timeline_webview.py
  src/windows/views/transitions_listview.py
  src/windows/views/transitions_treeview.py
  src/windows/views/tutorial.py
Labels: 💡 enhancement

#3522 Add new OSP icon, install & use
  setup.py
  xdg/openshot-qt-doc.svg
  xdg/org.openshot.OpenShot.xml
Labels: OS:Linux

#3520 Titles: Don't pollute temp dir with title previews
  src/windows/title_editor.py
Labels: closer, media-handling
