Repository OpenShot/openshot-qt, pull requests merged in 2022-02, with the labels that each got.

#4653 STY: Using bool on comparisons is not necessary
  src/classes/logger.py
  src/windows/main_window.py
  src/windows/views/blender_listview.py
Labels: code

#4637 Presets: Add MKV (h.264) sw/hw presets
  src/presets/format_mkv_x264.xml
  src/presets/format_mkv_x264_dx.xml
  src/presets/format_mkv_x264_hw.xml
  src/presets/format_mkv_x264_nv.xml
  src/presets/format_mkv_x264_qsv.xml
  src/presets/format_mkv_x264_vtb.xml
Labels: media-handling

#4656 Freeze and unfreeze toolbar along with other windows.
  src/windows/main_window.py
Labels: interface

#4630 Fix viewport zooming and region selection
  src/windows/video_widget.py
Labels: interface
